name: '[CI] Continuous Integration'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.4.0'

      - name: Debug
        run: 'ls -la'

      - name: Install Dependencies
        run: 'npm ci'

      - name: Lint
        run: 'npm run lint'

  UniTtest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.4.0'

      - name: Debug
        run: 'ls -la'

      - name: Install Dependencies
        run: 'npm ci'

      - name: Unit test
        run: 'npm run test'

  E2Etest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.4.0'

      - name: Debug
        run: 'ls -la'

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_FIREBASE_APP_API_KEY: ${{ secrets.FIREBASE_APP_API_KEY }}
          envkey_FIREBASE_APP_AUTH_DOMAIN: ${{ secrets.FIREBASE_APP_AUTH_DOMAIN }}
          envkey_FIREBASE_APP_PROJECT_ID: ${{ secrets.FIREBASE_APP_PROJECT_ID }}
          envkey_FIREBASE_APP_STORAGE_BUCKET: ${{ secrets.FIREBASE_APP_STORAGE_BUCKET }}
          envkey_FIREBASE_APP_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_APP_MESSAGING_SENDER_ID }}
          envkey_FIREBASE_APP_APP_ID: ${{ secrets.FIREBASE_APP_APP_ID }}
          envkey_FIREBASE_APP_MEASUREMENT_ID: ${{ secrets.FIREBASE_APP_MEASUREMENT_ID }}
          envkey_USER_EMAIL: ${{ secrets.USER_EMAIL }}
          envkey_USER_PASSWORD: ${{ secrets.USER_PASSWORD}}

      - name: Install Dependencies
        run: 'npm install'

      - name: E2e test
        run: 'npm run test:e2e'
