name: '[CI] Continuous Integration'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: pnpm setup
        uses: pnpm/action-setup@v2.4.0

      - name: Debug
        run: 'ls -la'

      - name: Install Dependencies
        run: 'pnpm install'

      - name: Lint
        run: 'pnpm run lint'
